### ISSUE TITLE
training and testing and dataset preparation script 

### ISSUE THREAD

**Issue by lerndeep** [goldblum/AdversarialQuerying#1]
could you provide training, testing and how to prepare dataset script for better understand?

**Comment by goldblum** [comment]
Datasets can be downloaded from: 
https://drive.google.com/file/d/1fJAK5WZTjerW7EWHHQAR9pRJVNg1T1Y7/view?usp=sharing, https://drive.google.com/open?id=1nVGCTd9ttULRXFezh4xILQ9lUkg0WZCG, https://drive.google.com/file/d/1_ZsLyqI487NRDQhwvI7rg86FK3YAZvz1/view?usp=sharing, https://drive.google.com/file/d/1GjGMI0q3bgcpcB_CjI40fX54WgLPuTpS/view?usp=sharing

You will then have to change the data directories in each of the ./data/* files to wherever you choose to store the data on your machine.

You can run train with:
python train.py --save_path ./your_favorite_folder

Then, you can test with:
python test.py --load ./your_favorite_folder/best_model.pth

These will of course run a bunch of default options (dataset, architecture, head, etc) that you can change.  Let me know if you have any other questions!
