### ISSUE TITLE
about maml-adml

### ISSUE THREAD

**Issue by Herb2333** [goldblum/AdversarialQuerying#2]
Thank you  for your code and paper! However,why remove maml-adml files,i found comparative experiment on this two models in your paper,but there are not  maml-adml files in it.

**Comment by goldblum** [comment]
The MAML code is very different than the rest of this repo, so it would be like having two repos in one, and MAML is very far from state-of-the-art right now.  We wanted a clean implementation of AQ on well-performing meta-learners.
