### ISSUE TITLE
About normalization

### ISSUE THREAD

**Issue by Imane219** [goldblum/AdversarialQuerying#3]
Hi, thanks for your great work.
I wonder why in data/mini_imagenet.py, you don't use normalization.
![image](https://user-images.githubusercontent.com/48405078/187665630-2cf83c65-7742-46fc-a749-d801d70f645f.png)
Thanks for answering.

**Comment by goldblum** [comment]
Hi, we did this to make sure that the l-infinity attack bounds are correct.  This practice is common in the adversarial attack literature.  However, you can instead do normalization in the standard way and then clip the PGD attack differently for each channel depending on the normalization constants.
